# SQL Manager Lite for MySQL 5.5.3.46192
# ---------------------------------------
# Host     : localhost
# Port     : 3306
# Database : fidelizacion


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES latin1 */;

SET FOREIGN_KEY_CHECKS=0;

CREATE DATABASE `fidelizacion`
    CHARACTER SET 'utf8'
    COLLATE 'utf8_general_ci';

USE `fidelizacion`;

#
# Structure for the `direccion` table : 
#

CREATE TABLE `direccion` (
  `ID_DIRECCION` INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `CALLE` VARCHAR(50) COLLATE latin1_swedish_ci DEFAULT NULL,
  `NUMERO` VARCHAR(50) COLLATE latin1_swedish_ci DEFAULT NULL,
  `LOCALIDAD` VARCHAR(50) COLLATE latin1_swedish_ci DEFAULT NULL,
  `PROVINCIA` VARCHAR(50) COLLATE latin1_swedish_ci DEFAULT NULL,
  `PAIS` VARCHAR(50) COLLATE latin1_swedish_ci DEFAULT NULL,
  PRIMARY KEY (`ID_DIRECCION`) USING BTREE
) ENGINE=InnoDB
AUTO_INCREMENT=1 ROW_FORMAT=DYNAMIC CHARACTER SET 'latin1' COLLATE 'latin1_swedish_ci'
;

#
# Structure for the `cliente` table : 
#

CREATE TABLE `cliente` (
  `ID_CLIENTE` INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(50) COLLATE latin1_swedish_ci NOT NULL,
  `APELLIDO` VARCHAR(50) COLLATE latin1_swedish_ci NOT NULL,
  `DNI` VARCHAR(50) COLLATE latin1_swedish_ci NOT NULL,
  `TELEFONO` VARCHAR(50) COLLATE latin1_swedish_ci DEFAULT NULL,
  `ID_DIRECCION` INTEGER(11) UNSIGNED NOT NULL,
  `MAIL` VARCHAR(100) COLLATE latin1_swedish_ci DEFAULT NULL,
  `FECHA_NACIMIENTO` DATE DEFAULT NULL,
  `FECHA_ALTA` DATE NOT NULL,
  `PUNTOS_ACUMULADOS` INTEGER(11) DEFAULT NULL,
  PRIMARY KEY (`ID_CLIENTE`) USING BTREE,
  UNIQUE KEY `dni_UNIQUE` (`DNI`) USING BTREE,
  UNIQUE KEY `ID_DIRECCION` (`ID_DIRECCION`) USING BTREE,
  KEY `FK_CLIENTE_DIRECCION_idx` (`ID_DIRECCION`) USING BTREE,
  CONSTRAINT `cliente_fk1` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `direccion` (`ID_DIRECCION`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB
AUTO_INCREMENT=1 ROW_FORMAT=DYNAMIC CHARACTER SET 'latin1' COLLATE 'latin1_swedish_ci'
;

#
# Structure for the `premio` table : 
#

CREATE TABLE `premio` (
  `ID_PREMIO` INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `DETALLE` VARCHAR(150) COLLATE latin1_swedish_ci NOT NULL,
  `PUNTOS` INTEGER(11) NOT NULL,
  `STOCK` INTEGER(11) NOT NULL,
  `ACTIVO` TINYINT(1) NOT NULL DEFAULT 1,
  `ANIVERSARIO` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID_PREMIO`) USING BTREE
) ENGINE=InnoDB
AUTO_INCREMENT=1 ROW_FORMAT=DYNAMIC CHARACTER SET 'latin1' COLLATE 'latin1_swedish_ci'
;

#
# Structure for the `canje` table : 
#

CREATE TABLE `canje` (
  `ID_CANJE` INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_PREMIO` INTEGER(11) UNSIGNED NOT NULL,
  `ID_CLIENTE` INTEGER(11) UNSIGNED NOT NULL,
  `FECHA` DATE NOT NULL,
  PRIMARY KEY (`ID_CANJE`) USING BTREE,
  KEY `fk_canje_cliente_idx` (`ID_CLIENTE`) USING BTREE,
  KEY `fk_canje_premio_idx` (`ID_PREMIO`) USING BTREE,
  CONSTRAINT `canje_fk1` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente` (`ID_CLIENTE`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `canje_fk2` FOREIGN KEY (`ID_PREMIO`) REFERENCES `premio` (`ID_PREMIO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB
AUTO_INCREMENT=1 ROW_FORMAT=DYNAMIC CHARACTER SET 'latin1' COLLATE 'latin1_swedish_ci'
;

#
# Structure for the `compra` table : 
#

CREATE TABLE `compra` (
  `ID_COMPRA` INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_CLIENTE` INTEGER(11) UNSIGNED NOT NULL,
  `FECHA` DATE NOT NULL,
  `PUNTOS` INTEGER(11) NOT NULL,
  PRIMARY KEY (`ID_COMPRA`) USING BTREE,
  KEY `fk_compra_cliente_idx` (`ID_CLIENTE`) USING BTREE,
  CONSTRAINT `compra_fk1` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente` (`ID_CLIENTE`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB
AUTO_INCREMENT=1 ROW_FORMAT=DYNAMIC CHARACTER SET 'latin1' COLLATE 'latin1_swedish_ci'
;

#
# Structure for the `producto` table : 
#

CREATE TABLE `producto` (
  `ID_PRODUCTO` INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `DETALLE` VARCHAR(50) COLLATE latin1_swedish_ci NOT NULL,
  `PUNTOS` INTEGER(11) NOT NULL,
  PRIMARY KEY (`ID_PRODUCTO`) USING BTREE
) ENGINE=InnoDB
AUTO_INCREMENT=1 ROW_FORMAT=DYNAMIC CHARACTER SET 'latin1' COLLATE 'latin1_swedish_ci'
;

#
# Structure for the `detalle_compra` table : 
#

CREATE TABLE `detalle_compra` (
  `ID_DETALLE_COMPRA` INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_COMPRA` INTEGER(11) UNSIGNED NOT NULL,
  `ID_PRODUCTO` INTEGER(11) UNSIGNED NOT NULL,
  `CANTIDAD` INTEGER(11) NOT NULL,
  `PUNTOS` INTEGER(11) NOT NULL,
  PRIMARY KEY (`ID_DETALLE_COMPRA`) USING BTREE,
  KEY `fk_detcom_compra_idx` (`ID_COMPRA`) USING BTREE,
  KEY `fk_detcom_prod_idx` (`ID_PRODUCTO`) USING BTREE,
  CONSTRAINT `detalle_compra_fk1` FOREIGN KEY (`ID_COMPRA`) REFERENCES `compra` (`ID_COMPRA`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `detalle_compra_fk2` FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `producto` (`ID_PRODUCTO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB
AUTO_INCREMENT=1 ROW_FORMAT=DYNAMIC CHARACTER SET 'latin1' COLLATE 'latin1_swedish_ci'
;

#
# Structure for the `parametro` table : 
#

CREATE TABLE `parametro` (
  `ID_PARAMETRO` INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(150) COLLATE latin1_swedish_ci NOT NULL,
  `VALOR` VARCHAR(50) COLLATE latin1_swedish_ci NOT NULL,
  PRIMARY KEY (`ID_PARAMETRO`) USING BTREE
) ENGINE=InnoDB
AUTO_INCREMENT=1 ROW_FORMAT=DYNAMIC CHARACTER SET 'latin1' COLLATE 'latin1_swedish_ci'
;

#
# Structure for the `puntos` table : 
#

CREATE TABLE `puntos` (
  `ID_PUNTOS` INTEGER(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_CLIENTE` INTEGER(11) UNSIGNED NOT NULL,
  `PUNTOS` INTEGER(11) NOT NULL,
  `FECHA` DATE NOT NULL,
  `ACTIVO` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID_PUNTOS`) USING BTREE,
  KEY `FK_PUNTOS_CLIENTES_idx` (`ID_CLIENTE`) USING BTREE,
  CONSTRAINT `puntos_fk1` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente` (`ID_CLIENTE`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB
AUTO_INCREMENT=1 ROW_FORMAT=DYNAMIC CHARACTER SET 'latin1' COLLATE 'latin1_swedish_ci'
;



/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;