package com.mercadolibre.academy.fidelizacion.modelo.entity;

// default package
// Generated 19-feb-2016 10:42:58 by Hibernate Tools 4.3.1.Final

/**
 * Direccion generated by hbm2java
 */
public class Direccion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5874620437032691984L;
	private Integer idDireccion;
	private String calle;
	private String numero;
	private String localidad;
	private String provincia;
	private String pais;
	private Cliente cliente;

	public Direccion() {
	}

	public Direccion(String calle, String numero, String localidad, String provincia, String pais, Cliente cliente) {
		this.calle = calle;
		this.numero = numero;
		this.localidad = localidad;
		this.provincia = provincia;
		this.pais = pais;
		this.cliente = cliente;
	}

	public Integer getIdDireccion() {
		return this.idDireccion;
	}

	public void setIdDireccion(Integer idDireccion) {
		this.idDireccion = idDireccion;
	}

	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

}
