package com.mercadolibre.academy.fidelizacion.modelo.entity;

// default package
// Generated 19-feb-2016 10:42:58 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5646411710957456627L;
	private Integer idProducto;
	private String detalle;
	private int puntos;
	private Set<DetalleCompra> detalleCompras = new HashSet<DetalleCompra>(0);

	public Producto() {
	}

	public Producto(String detalle, int puntos) {
		this.detalle = detalle;
		this.puntos = puntos;
	}

	public Producto(String detalle, int puntos, Set<DetalleCompra> detalleCompras) {
		this.detalle = detalle;
		this.puntos = puntos;
		this.detalleCompras = detalleCompras;
	}

	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

	public int getPuntos() {
		return this.puntos;
	}

	public void setPuntos(int puntos) {
		this.puntos = puntos;
	}

	public Set<DetalleCompra> getDetalleCompras() {
		return this.detalleCompras;
	}

	public void setDetalleCompras(Set<DetalleCompra> detalleCompras) {
		this.detalleCompras = detalleCompras;
	}

}
